### ISSUE TITLE
Questions about wakaba

### ISSUE THREAD

**Issue by hsimons** [sora-chan/wakaba#1] opened 2015-08-05 00:06 UTC
http://bbs.progrider.org/prog/read/1438725091

**Comment by sora-chan** [comment] 2015-08-05 02:21
>Interesting. How do I use this with curl?
https://wakaba.dhcp.io
>Where are the uploaded files saved?
On the filesystem, the server will reply back with a URL.

>1. It says it's asynchronous but that's a load of bull. The pool workers stay dormant while writing and reading, plus they assume all writes are not interrupted. This is a very half assed job.
What do you mean by this? if one thread is blocking because of a read or write, that doesn't mean that every other thread is blocking too, one thread is assigned to each client and the client is served asynchronously unaffected by any other threads/clients (except for bandwidth obviously).
>2. POSIX mutexes.
And?

>HTTP is a disgusting protocol.
I absolutely agree.

>But if it uses openssl it's fucked.
Also agree, OpenSSL is such a shit, I'm trying to figure out a bug that seems to happen randomly in SSL_accept, i think it might have something to do with my multi threaded code, maybe I'm doing something wrong, but either way, OpenSSL is pretty shit, i might just switch to GNUTLS if all fails.

Any other questions? (also I'm surprised this spread to another website in this small time, are web applications written in C really that rare?).

**Comment by sora-chan** [comment] 2015-08-05 02:26
Woops, fucked up quotes there, and Github is giving me errors when trying to edit.

**Comment by gonmf** [comment] 2015-08-05 12:18
>What do you mean by this? if one thread is blocking because of a read or write, that doesn't mean that every other thread is blocking too, one thread is assigned to each client and the client is served asynchronously unaffected by any other threads/clients (except for bandwidth obviously).

What I meant was, since the I/O will actually be dealt with by the kernel, the worker pool threads should be freed to to do more useful things in the meanwhile. An actual assynchronous server would make the sockets non blocking, and just call the system calls for reading and writing. The kernel provides multiple functions to, in a non-blocking manner, ask if any of the file descriptors meet some specified event types (like EOF).

In linux you have the poll, select and epoll functions. epoll is the more recent and more powerful one, the other two suffer a performance hit with a very large number of file descriptors (because they perform a linear search).

If you want to learn more I suggest you read their manpages and a proper explanation on building high performance I/O applications using epoll.

It wouldn't be easy to adapt your project to use epoll or other assynchronous models based on polling, and there are many servers that use your model (like Apache); so this is more of a suggestion for a future project.

Finally, you also don't check whether reads and writes succeed, which can be a serious issue.

> POSIX mutexes.
They look ugly and sempahores are objectively superior. But more on point is the fact you only  seem to use them briefly for disputed resources; instead you could use a simple spin lock implementation with atomic operations. You can read the kernel implementation for this. I think it would look much clearer but I haven't read your code enough to say whether or not it is better for the threads to concede execution or to actively wait on the resource.

**Comment by sora-chan** [comment] 2015-08-05 13:03
>What I meant was, since the I/O will actually be dealt with by the kernel, the worker pool threads should be freed to to do more useful things in the meanwhile. An actual assynchronous server would make the sockets non blocking, and just call the system calls for reading and writing. The kernel provides multiple functions to, in a non-blocking manner, ask if any of the file descriptors meet some specified event types (like EOF).

Maybe asynchronous wasn't the right word to use then, because what you described is not my intention.

>Finally, you also don't check whether reads and writes succeed, which can be a serious issue.

Will fix this tomorrow, I'm too tired right now.

>They look ugly and sempahores are objectively superior. But more on point is the fact you only seem to use them briefly for disputed resources; instead you could use a simple spin lock implementation with atomic operations. You can read the kernel implementation for this. I think it would look much clearer but I haven't read your code enough to say whether or not it is better for the threads to concede execution or to actively wait on the resource.

This is the first time I've done multi threading so excuse my inexperience, but i will check out semaphores.

**Comment by gonmf** [comment] 2015-08-05 13:08
Cool, also check the C10k problem if you're interested.

**Closed** 2015-08-05 13:10 UTC

**Comment by sora-chan** [comment] 2015-08-06 07:13
>Finally, you also don't check whether reads and writes succeed, which can be a serious issue.

But i do:
```c
if (SSL_write(cc->ssl, buf, packetsize) <= 0)
	break;
```

Or are you talking about something else?

**Comment by gonmf** [comment] 2015-08-06 13:24
The functions fwrite, fread, remove and *alloc have return values and are not guaranteed to read/write the amounts specified. Not checking *alloc is specially serious.
The functions close, fclose, *print*, scan*, kill also have return values even if no one checks them.

I'm gonna continue and point out everything I think could be better in a single post.

You could use the symbols bool, true, false, NULL, EXIT_SUCCESS, EXIT_FAILURE, etc and generate comprehensive error messages; instead of using logical comparison with strcmp and the like (!strcmp(...)); it's more confusing.

Some things are static, some things that could be are not, it's hard to understand the rationale behind it. Some functions parameters could also be const. Both of this should be good for performance  overall.

free(node->data);
	if (node == file_list)
		file_list = file_list->next;
This crashes the program I think. The function cache_data does the same thing, following pointers in structures already freed.

The functions cache_terminate, socket_terminate and database_terminate don't unlock their mutexes, don't know if this was intended.

In function database_rm you could reuse the same buffer.

In function process_admincmd your comparison with strcmp probably needs to be negated to work.

In function process_request case EINVAL is not used.

In function socket_https_listener you use the word fag which is a big no-no for our SJW github overlords.

In function load_bans the shared lock is not used.

I think that's all at first glance.

**Comment by sora-chan** [comment] 2015-08-06 15:00
>The functions fwrite, fread, remove and alloc have return values and are not guaranteed to read/write the amounts specified. Not checking *alloc is specially serious.
The functions close, fclose, *print, scan*, kill also have return values even if no one checks them.

Honestly this never happens on modern systems, I'm not going to bloat up the code by adding those checks.

>You could use the symbols bool, true, false, NULL, EXIT_SUCCESS, EXIT_FAILURE, etc

I prefer straight integer values, unless they're platform dependant.

>using logical comparison with strcmp and the like (!strcmp(...)); it's more confusing.

I don't really see a problem with it, other than someone new to C standard library thinking that the ! means that it's saying "If the string doesn't match" when it's actually the other way around.

>Some things are static, some things that could be are not, it's hard to understand the rationale behind it. Some functions parameters could also be const. Both of this should be good for performance overall.

You have a point, i might fix that up in a commit, but it's not all that important.

>```c
free(node->data);
if (node == file_list)
file_list = file_list->next;
```
This crashes the program I think. The function cache_data does the same thing, following pointers in structures already freed.

No it wouldn't, freeing node->data is not freeing the whole node structure.

>The functions cache_terminate, socket_terminate and database_terminate don't unlock their mutexes, don't know if this was intended.

I am aware of this, but i figured it didn't really matter because the program is terminating anyway.

>In function database_rm you could reuse the same buffer.

Will fix.

>In function process_admincmd your comparison with strcmp probably needs to be negated to work.

It's checking weather the given password does NOT match the set password, it's correct.

>In function socket_https_listener you use the word fag which is a big no-no for our SJW github overlords.

I don't care, I'll just move somewhere else if it gets taken down.

>In function load_bans the shared lock is not used.

It's locked in `socket_ban`, which `socket_loadbans` calls.
